CREATE TABLE public.m_role (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	created_by int8 NULL,
	updated_by int8 NULL,
	created_by_name varchar(255) NULL,
	updated_by_name varchar(255) NULL,
	CONSTRAINT m_role_pkey PRIMARY KEY (id)
);

CREATE TABLE public.m_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	username varchar(255) NULL,
	"password" varchar(255) NULL,
	role_id int8 NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	created_by int8 NULL,
	updated_by int8 NULL,
	created_by_name varchar(255) NULL,
	updated_by_name varchar(255) NULL,
	CONSTRAINT m_user_pkey PRIMARY KEY (id),
	CONSTRAINT user_role_id FOREIGN KEY (role_id) REFERENCES public.m_role (id)
);