CREATE TABLE public.m_role (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	created_by int8 NULL,
	updated_by int8 NULL,
	created_by_name varchar(255) NULL,
	updated_by_name varchar(255) NULL,
	CONSTRAINT m_role_pkey PRIMARY KEY (id)
);

CREATE TABLE public.m_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	username varchar(255) NULL,
	"password" varchar(255) NULL,
	role_id int8 NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	created_by int8 NULL,
	updated_by int8 NULL,
	created_by_name varchar(255) NULL,
	updated_by_name varchar(255) NULL,
	CONSTRAINT m_user_pkey PRIMARY KEY (id),
	CONSTRAINT user_role_id FOREIGN KEY (role_id) REFERENCES public.m_role (id)
);

CREATE TABLE public.t_refresh_token (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	token varchar(255) NULL,
	validity timestamp(6) NULL,
	user_id int8 NULL,
	CONSTRAINT t_refresh_token_pkey PRIMARY KEY (id),
	CONSTRAINT refresh_token_user_id FOREIGN KEY (user_id) REFERENCES public.m_user (id)
);

CREATE TABLE public.m_position (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	created_by int8 NULL,
	updated_by int8 NULL,
	created_by_name varchar(255) NULL,
	updated_by_name varchar(255) NULL,
	CONSTRAINT m_position_pkey PRIMARY KEY (id)
);

CREATE TABLE public.m_basic_salary (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	salary_amount int8 NULL,
	total_year int4 NULL,
	position_id int8 NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	created_by int8 NULL,
	updated_by int8 NULL,
	created_by_name varchar(255) NULL,
	updated_by_name varchar(255) NULL,
	CONSTRAINT m_basic_salary_pkey PRIMARY KEY (id),
	CONSTRAINT basic_salary_position_id FOREIGN KEY (position_id) REFERENCES public.m_position (id)
);