CREATE TABLE public.m_role (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	created_by int8 NULL,
	updated_by int8 NULL,
	created_by_name varchar(255) NULL,
	updated_by_name varchar(255) NULL,
	is_deleted bool NULL,
	CONSTRAINT m_role_pkey PRIMARY KEY (id)
);