package constant

const CONFIG_FILE = "application.yaml"
const DB_HOST = "database.host"
const DB_USERNAME = "database.username"
const DB_PASSWORD = "database.password"
const DB_NAME = "database.name"
const DB_PORT = "database.port"
const SYSTEM = "system"
const PREFIX_API = "/api"
const ID = "id"
const APP_HOST = "localhost:8080"
const ERROR = "Error : "
const SEARCH = "search"
const PAGE_NUMBER = "pageNumber"
const PAGE_SIZE = "pageSize"
const IS_DELETED_FALSE = "is_deleted = false"
