package constant

const CONFIG_FILE = "application.yaml"
const DB_HOST = "database.host"
const DB_USERNAME = "database.username"
const DB_PASSWORD = "database.password"
const DB_NAME = "database.name"
const DB_PORT = "database.port"
const JWT_KEY = "jwt.key"
const JWT_EXPIRED = "jwt.expired"
const APP_NAME = "app.name"
const SYSTEM = "system"
const PREFIX_API = "/api"
const ID = "id"
const APP_HOST = "localhost:8080"
const ERROR = "Error : "
const SEARCH = "search"
const PAGE_NUMBER = "pageNumber"
const PAGE_SIZE = "pageSize"
const MIN_PASSWORD_LEN = 10
const SIGNING_METHOD_INVALID = "signing method invalid"
const AUTHORIZATION = "Authorization"
const BEARER = "Bearer "
const HEADER = "header"
