package constant

const SUCCESS = "sukses"
const DATA_NOT_FOUND = "data tidak ditemukan"
const ROLE_NOT_FOUND = "role tidak ditemukan"
const USER_NOT_FOUND = "user tidak ditemukan"
const POSITION_NOT_FOUND = "jabatan tidak ditemukan"
const BASIC_SALARY_NOT_FOUND = "gaji pokok tidak ditemukan"
const ALLOWANCE_TYPE_NOT_FOUND = "jenis tunjangan tidak ditemukan"
const ALLOWANCE_NOT_FOUND = "tunjangan tidak ditemukan"
const USERNAME_ALREADY_REGISTERED = "username telah terdaftar"
const PASSWORD_MIN_10 = "password minimal 10 karakter"
const PASSWORD_DIGIT_UPPER_LOWER = "password harus ada angka, huruf kapital dan huruf kecil"
const CANNOT_DELETE_THIS_DATA = "tidak bisa menghapus data ini"
const UNAUTHORIZED = "unauthorized"
const WRONG_USERNAME_PASSWORD = "username atau password salah"
const TOKEN_NOT_VALID = "token tidak sah"
const INTERNAL_SERVER_ERROR = "internal server error"
const TOTAL_YEAR_ALREADY_EXIST = "jumlah tahun kerja telah terdaftar"
