basePath: /api
definitions:
  request.RoleRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  response.PaginationResponse:
    properties:
      data: {}
      pageNumber:
        type: integer
      pageSize:
        type: integer
      totalItem:
        type: integer
      totalPage:
        type: integer
    type: object
  response.RoleResponse:
    properties:
      createdAt:
        type: string
      createdBy:
        type: integer
      createdByName:
        type: string
      id:
        type: integer
      isDeleted:
        type: boolean
      name:
        type: string
      updatedAt:
        type: string
      updatedBy:
        type: integer
      updatedByName:
        type: string
    type: object
  response.WebResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a payroll api service.
  title: PAYROLL API
  version: "1.0"
paths:
  /roles:
    get:
      consumes:
      - application/json
      parameters:
      - description: Search
        in: query
        name: search
        type: string
      - default: "1"
        description: Page Number
        in: query
        name: pageNumber
        type: string
      - default: "10"
        description: Page Size
        in: query
        name: pageSize
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.WebResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.PaginationResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.WebResponse'
      tags:
      - Role
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.RoleResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.WebResponse'
      tags:
      - Role
  /roles/all:
    get:
      consumes:
      - application/json
      parameters:
      - description: Search
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.WebResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/response.RoleResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.WebResponse'
      tags:
      - Role
  /roles/id/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.RoleResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.WebResponse'
      tags:
      - Role
    put:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.WebResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.RoleResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.WebResponse'
      tags:
      - Role
swagger: "2.0"
